import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import { Slide, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import { ClerkProvider } from '@clerk/nextjs';
// import { Provider } from "./providers";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  subsets: ["latin"],
  weight: "100"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      {/* <Provider> */}
        <html lang="en" suppressHydrationWarning>
          <body className={`${inter.className} ${roboto.className} antialiased`}>
            {children ? children : <div style={{ color: "red" }}>Error rendering content</div>}

            <ToastContainer
              position="bottom-right"
              theme="colored"
              autoClose={1000}
              closeOnClick
              pauseOnHover
              transition={Slide}
              hideProgressBar
              draggable
            />
          </body>
        </html>
      {/* </Provider> */}
    </ClerkProvider>
  );
}
